org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=ratbridge
mod_name=RatBridge
mod_group_id=datrat.ratbridge
mod_version=0.1.10
mod_authors=datrat
mod_license=MIT
mod_description=Server-side bridge between Minecraft and external chat clients.
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.2
forge_version_range=[47,)
loader_version_range=[47,)
fabric_minecraft_version=1.20.1
fabric_minecraft_version_range=>=1.20.1 <1.20.2
fabric_loader_version=0.16.14
fabric_api_version=0.92.9+1.20.1
neoforge_minecraft_version=1.20.2
neoforge_minecraft_version_range=[1.20.2,1.20.3)
neoforge_version=20.2.93
neoforge_version_range=[20.2,)
neoforge_loader_version_range=[1,)
jda_version=6.4.2
