org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mod_id=simplebridge
mod_name=Simple Bridge
mod_group_id=datrat.simplebridge
mod_version=0.1.0
mod_authors=datrat
mod_license=MIT
mod_description=Server-side bridge between Minecraft Forge and external chat clients.
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.2
forge_version_range=[47,)
loader_version_range=[47,)
jda_version=6.4.2
